controller:
  hostNetwork: "true"
  dnsPolicy: ClusterFirstWithHostNet
  extraContainers:
    - name: prometheus-to-sd
      image: gcr.io/google-containers/prometheus-to-sd:v0.9.2
      ports:
        - name: profiler  
          containerPort: 6060
      command: ["/monitor"]
      args:
      - --source=nginx-ingress-controller:http://localhost:10254/metrics
      - --stackdriver-prefix=custom.googleapis.com
      - --pod-id=$(POD_NAME)
      - --namespace-id=$(POD_NAMESPACE)
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
  metrics:
    enabled: "true"
